indi_setprop "EQMod Mount.CONNECTION.CONNECT=On"
indi_setprop "EQMod Mount.HORIZONLIMITSONLIMIT.HORIZONLIMITSONLIMITTRACK=Off"
indi_setprop "EQMod Mount.TELESCOPE_TRACK_MODE.TRACK_LUNAR=On"
indi_setprop "EQMod Mount.TELESCOPE_TRACK_STATE.TRACK_ON=On"
